#!/system/bin/sh
#
# mount ext4 partition from sd card

BB="logwrapper busybox";

if [ "$SD_EXT_DIRECTORY" = "" ];
then
    SD_EXT_DIRECTORY=/sd-ext;
fi;

# find SD Card
for i in `seq 0 9`;
do
    ISSD=`cat /sys/block/mmcblk$i/device/type`
    if [ "$ISSD" = "SD" ];
    then
        SDCARD=/dev/block/mmcblk$i
        break
    fi
done

# wait for the device to settle
COUNT=6;
until [ -b "$SDCARD" ] || [ $COUNT -lt 1 ];
do
    sleep 1;
    COUNT=$((COUNT-1));
done;

if [ -b "$SDCARD" ];
then
    # find sd-ext partition by label
    for i in `seq 1 16`;
    do
        if [ -b ${SDCARD}p${i} ];
        then
            LABEL=`e2label ${SDCARD}p${i}`
            if [ "$LABEL" = "sd-ext" ];
            then
                PARTITION=${SDCARD}p${i}
                break
            fi
        else
            break
        fi
    done
    
    if [ -b "$PARTITION" ];
    then
        log -p i -t mountsd "Checking filesystems..";
   
        # fsck the sdcard filesystem first
        if [ -x `which e2fsck` ];
        then
            e2fsck -y $PARTITION;e2fsk_exitcode=$?
        else
            echo "executable e2fsck not found, assuming no filesystem errors"
            e2fsk_exitcode=0
        fi
        # set property with exit code in case an error occurs
        setprop cm.e2fsck.errors $e2fsk_exitcode;
        if [ "$e2fsk_exitcode" -lt 2 ];
        then
            # mount and set perms
            $BB mount -o noatime,barrier=1,data=ordered,noauto_da_alloc -t ext4 $PARTITION $SD_EXT_DIRECTORY;
            if [ "$?" = 0 ];
            then
                $BB chown 1000:1000 $SD_EXT_DIRECTORY;
                $BB chmod 771 $SD_EXT_DIRECTORY;
                log -p i -t mountsd "$SD_EXT_DIRECTORY successfully mounted";
            else
                log -p e -t mountsd "Unable to mount filesystem for $SD_EXT_DIRECTORY!";
            fi
        else
            log -p e -t mountsd "Unable to repair filesystem, disabling apps2sd";
        fi
    fi
fi
