PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/kmobs_ace.mk \
    $(LOCAL_DIR)/kmobs_blade.mk \
    $(LOCAL_DIR)/kmobs_bravo.mk \
    $(LOCAL_DIR)/kmobs_bravoc.mk \
    $(LOCAL_DIR)/kmobs_buzz.mk \
    $(LOCAL_DIR)/kmobs_click.mk \
    $(LOCAL_DIR)/kmobs_crespo.mk \
    $(LOCAL_DIR)/kmobs_desirec.mk \
    $(LOCAL_DIR)/kmobs_dream_sapphire.mk \
    $(LOCAL_DIR)/kmobs_encore.mk \
    $(LOCAL_DIR)/kmobs_espresso.mk \
    $(LOCAL_DIR)/kmobs_hero.mk \
    $(LOCAL_DIR)/kmobs_heroc.mk \
    $(LOCAL_DIR)/kmobs_inc.mk \
    $(LOCAL_DIR)/kmobs_generic.mk \
    $(LOCAL_DIR)/kmobs_glacier.mk \
    $(LOCAL_DIR)/kmobs_harmony.mk \
    $(LOCAL_DIR)/kmobs_legend.mk \
    $(LOCAL_DIR)/kmobs_leo.mk \
    $(LOCAL_DIR)/kmobs_liberty.mk \
    $(LOCAL_DIR)/kmobs_one.mk \
    $(LOCAL_DIR)/kmobs_passion.mk \
    $(LOCAL_DIR)/kmobs_sholes.mk \
    $(LOCAL_DIR)/kmobs_speedy.mk \
    $(LOCAL_DIR)/kmobs_supersonic.mk \
    $(LOCAL_DIR)/kmobs_vega.mk \
    $(LOCAL_DIR)/kmobs_vision.mk \
    $(LOCAL_DIR)/kmobs_z71.mk \
    $(LOCAL_DIR)/kmobs_zeppelin.mk \
    $(LOCAL_DIR)/kmobs_zero.mk
